services:
  mongo:
    image: mongo:6
    container_name: mongocontainer
    restart: always
    ports:
      - "3400:3400"
    volumes:
      - mongodb:/data/db
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back_end
    restart: always

    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://sanjitpal:sanjitpal123@cluster0.2c7cetn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  frontend:
    build:
      context: ./front-end/mentorfont-end
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  mongodb:
