import express from "express";
import AuthRouter from "./Auth.js";
import UserRouter from "./userRoute.js";
import SessionRouter from "./Session.js";
import ConvoRouter from "./Convo.js";
import MessageRouter from "./Message.js";
import MentorRouter from "./Mentorroute.js";
import MenteeRouter from "./MenteeRouter.js";
import WishListRouter from "./WishList.js";
import NotificationRouter from "./NotificationRouter.js";
const MainRouter = express.Router();
MainRouter.use("/auth", AuthRouter);
MainRouter.use("/user", UserRouter);
MainRouter.use("/session", SessionRouter);
MainRouter.use("/convo", ConvoRouter);
MainRouter.use("/message", MessageRouter);
MainRouter.use("/mentor", MentorRouter);
MainRouter.use("/mentee", MenteeRouter);
MainRouter.use("/wishlist", WishListRouter);
MainRouter.use("/notification", NotificationRouter);
export default MainRouter;
